@startuml sequence
actor User

User -> MazeRunner: Run MazeRunner
activate MazeRunner
MazeRunner -> Configuration: Configure(args)
activate Configuration
Configuration --> MazeRunner: Configuration
deactivate Configuration
MazeRunner -> Maze: new Maze(inputFile)
activate Maze
Maze --> MazeRunner: Maze
deactivate Maze
MazeRunner -> BreadthFirstSearch: new BreadthFirstSearch(maze)
activate BreadthFirstSearch
BreadthFirstSearch --> MazeRunner: BreadthFirstSearch
deactivate BreadthFirstSearch
MazeRunner -> BreadthFirstSearch: breadthFirstSearch()
activate BreadthFirstSearch
BreadthFirstSearch --> BreadthFirstSearch: BFS algorithm
deactivate BreadthFirstSearch
MazeRunner --> User: Path
deactivate MazeRunner
@enduml
